import type { DeskSection, DeskSectionId } from "./types";

export const HERO_IMAGE_WIDTH = 1672;
export const HERO_IMAGE_HEIGHT = 941;
export const HERO_VIEW_BOX = `0 0 ${HERO_IMAGE_WIDTH} ${HERO_IMAGE_HEIGHT}`;

export const deskSections = [
  {
    id: "identity",
    label: "Identity",
    object: "monitor",
    eyebrow: "Woon Tak Yuh, MD",
    title: "Spine surgeon, educator, and clinical AI builder.",
    summary:
      "A living desk for the work I am actually doing: endoscopic spine surgery, surgical education, research, AI workflow, presentations, and field notes.",
    bullets: [
      "Director, Center for Endoscopic Spine Surgery",
      "Davos Hospital, South Korea",
      "Public record synced from working databases",
    ],
    href: "/cv",
    hrefLabel: "Open living CV",
    secondaryHref: "/contact",
    secondaryHrefLabel: "Contact",
    accent: "#8bd3ff",
    layer: {
      kind: "image",
      src: "/desk-objects/profile-frame.webp",
      alt: "Framed portrait of a surgeon in the operating room",
      x: 88.3,
      y: 7.2,
      width: 9.6,
      height: 24.8,
      zIndex: 35,
    },
  },
  {
    id: "presentations",
    label: "Schedule",
    object: "calendar clock",
    eyebrow: "Schedule",
    title: "Talks, workshops, and live teaching time.",
    summary:
      "The calendar clock is a working object: current date and time on the desk, public schedule on the monitor.",
    bullets: ["Invited talks and workshops", "UBE, ERAS, AI workflow", "Recent and upcoming entries"],
    href: "/cv",
    hrefLabel: "Browse talks",
    secondaryHref: "/media",
    secondaryHrefLabel: "Teaching media",
    accent: "#d89055",
    layer: {
      kind: "live-clock",
      src: "/desk-objects/calendar-clock.webp",
      alt: "Live calendar clock showing your local time",
      x: 7.4,
      y: 62.6,
      width: 19.4,
      height: 22.6,
      zIndex: 42,
    },
  },
  {
    id: "surgery",
    label: "Spine Surgery",
    object: "spine model",
    eyebrow: "Clinical practice",
    title: "Endoscopic spine work with visible anchors.",
    summary:
      "UBE is treated as a surgical language: portal planning, field control, decompression logic, complication awareness, and registry-backed outcomes.",
    bullets: ["UBE and MISS", "Tumor and degenerative pathology", "Registry-aware outcomes"],
    href: "/ube",
    hrefLabel: "Explore UBE",
    secondaryHref: "/dashboard",
    secondaryHrefLabel: "Surgery dashboard",
    accent: "#4fc8b8",
    layer: {
      kind: "image",
      src: "/desk-objects/spine-model.webp",
      alt: "Anatomical lumbar spine model with pelvis",
      x: 71.6,
      y: 18.5,
      width: 12,
      height: 50,
      zIndex: 40,
      labelPosition: "bottom",
    },
  },
  {
    id: "research",
    label: "Research",
    object: "leather journal",
    eyebrow: "Publication record",
    title: "Research that stays close to the operating room.",
    summary:
      "Publication previews come from the same Notion-fed source as the CV, keeping the homepage current without becoming ornamental.",
    bullets: ["Endoscopic spine surgery", "Imaging and deep learning", "ERAS and outcomes data"],
    href: "/research",
    hrefLabel: "Read research",
    secondaryHref: "/cv",
    secondaryHrefLabel: "Publication record",
    accent: "#d7b65d",
    layer: {
      kind: "image",
      src: "/desk-objects/research-journal-pen.webp",
      alt: "Open leather research journal and fountain pen",
      x: 71.5,
      y: 62.7,
      width: 26.8,
      height: 28.8,
      zIndex: 43,
    },
  },
  {
    id: "education",
    label: "Education",
    object: "UBE textbook and PROM tablet",
    eyebrow: "Surgical education",
    title: "Education projects that turn endoscopy into a system.",
    summary:
      "The education layer connects UBE teaching projects, PROM development, beginner workshops, live teaching, and surgical mental models.",
    bullets: ["UBE training projects", "PROM development", "Cadaver and live workshops"],
    href: "/education",
    hrefLabel: "View education",
    secondaryHref: "/media",
    secondaryHrefLabel: "Workshop media",
    accent: "#9e91df",
    layer: {
      kind: "image",
      src: "/desk-objects/ube-prom-kit.webp",
      alt: "UBE textbook and PROM tablet",
      x: 87.2,
      y: 40.2,
      width: 12.8,
      height: 25.2,
      zIndex: 44,
    },
  },
  {
    id: "ai",
    label: "AI Workflow",
    object: "Mac mini M4",
    eyebrow: "Clinical AI",
    title: "AI as quiet infrastructure, not gadget theater.",
    summary:
      "Documentation continuity, registry structure, checklist support, and research synthesis sit under physician review.",
    bullets: ["Voice to structured notes", "Notion as living substrate", "LLM review layer"],
    href: "/ai",
    hrefLabel: "Open AI layer",
    secondaryHref: "/ai-workflow",
    secondaryHrefLabel: "Workflow map",
    accent: "#93d17e",
    layer: {
      kind: "image",
      src: "/desk-objects/mac-mini-m4.webp",
      alt: "Mac mini M4 AI workflow object",
      x: 38.5,
      y: 55.2,
      width: 18,
      height: 13.8,
      zIndex: 40,
    },
  },
  {
    id: "personal",
    label: "Personal",
    object: "family frame",
    eyebrow: "Personal signal",
    title: "A homepage should feel like a person, not a template.",
    summary:
      "The family frame holds the off-axis signal: tools, training, coding, family, movement, and the private logic behind public work.",
    bullets: ["Vibe coding and clinical tools", "BJJ, surfing, snowboarding", "Human signal, not mascot energy"],
    href: "/knowledge",
    hrefLabel: "Read notes",
    secondaryHref: "/cv",
    secondaryHrefLabel: "Living record",
    accent: "#dc7da8",
    layer: {
      kind: "image",
      src: "/desk-objects/family-frame.webp",
      alt: "Framed golden-hour family photo",
      x: 2.8,
      y: 36.5,
      width: 12,
      height: 21,
      zIndex: 38,
    },
  },
] satisfies readonly DeskSection[];

export const sectionById = new Map<DeskSectionId, DeskSection>(
  deskSections.map((section) => [section.id, section]),
);
